CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL DEFAULT '',
    state VARCHAR(10) NOT NULL DEFAULT 'IDLE', -- IDLE/MATCHING/IN_GAME

    password_hash VARCHAR(255) NOT NULL,    -- 用户密码的单向哈希 (Bcrypt)
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_users_name ON users(name);
