// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Dailiduzhou/the-verdict-paradox/backend/app/game/internal/biz"
	"github.com/Dailiduzhou/the-verdict-paradox/backend/app/game/internal/conf"
	"github.com/Dailiduzhou/the-verdict-paradox/backend/app/game/internal/data"
	"github.com/Dailiduzhou/the-verdict-paradox/backend/app/game/internal/server"
	"github.com/Dailiduzhou/the-verdict-paradox/backend/app/game/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	pool, cleanup, err := data.NewPgxPool(confData)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := data.NewRedisClient(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataData, cleanup3, err := data.NewData(pool, client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	authRepo := data.NewAuthRepo(client, logger)
	authUsecase := biz.NewAuthUsecase(userRepo, authRepo, auth)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(authUsecase, userUsecase, logger)
	matchRepo := data.NewMatchRepo(client, logger)
	gameService := service.NewGameService(userRepo, matchRepo, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, gameService, authUsecase, auth, logger)
	roomManager := biz.NewRoomManager(logger)
	httpServer := server.NewHTTPServer(confServer, userService, gameService, authUsecase, auth, roomManager, logger)
	matchUsecase := biz.NewMatchUsecase(matchRepo, logger)
	matchServer := server.NewMatchServer(matchUsecase, logger)
	app := newApp(logger, grpcServer, httpServer, matchServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
